default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: mmendesc
  password:

  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: repassa_development

test:
  <<: *default
  database: repassa_test

